script_version = "0.1"
config_name = "assessment_2025_03_05"  


flagging_approaches = [
    "Raunak2021ApproachConfig",
    "Guerreiro2023MCDSim",
    "Guerreiro2023SeqLogprob"
]

[resource_config]
    path_work_dir = "<a path directory where you want to save the results.>"
    path_dataset_tsv = "<a path where the halomi tsv file is located.>"

    # a directory that you want to save the translation outputs.
    path_dir_cache_translation = "<repalce here>"

[evaluation_config]

[approach_configs]
    [approach_configs.Raunak2021ApproachConfig]
        # a path of Python3.7 that NLArgumenter package is installed (See README)
        path_python37_exec = "<replace here>"

    [approach_configs.Guerreiro2023MCDSim]
        # please set the LFAN-HALL translation model (see README) and replace "<replace_here>"    
        path_fairseq_model_dir = "<replace here> /wmt18_de-en"
        path_fairseq_model_file = "<replace here> /checkpoint_best.pt"
        path_sentencepiece_model = "<replace here> /sentencepiece_models/sentencepiece.joint.bpe.model"

        num_samples = 10
        temperature_value = 1.0
        percentile = 40

        max_len_a = 1.0
        max_len_b = 10

    [approach_configs.Guerreiro2023SeqLogprob]
        # please set the LFAN-HALL translation model (see README) and replace "<replace_here>"    
        path_fairseq_model_dir = "<replace here> /wmt18_de-en"
        path_fairseq_model_file = "<replace here> /checkpoint_best.pt"
        path_sentencepiece_model = "<replace here> /sentencepiece_models/sentencepiece.joint.bpe.model"

        percentile_threshold = 40

        max_len_a = 1.0
        max_len_b = 10

